rm -f config.log
rm -f config.h
rm -f config.h.in
rm -f config.h.in~
rm -f config.nice
rm -f config.status
rm -f configure
rm -f configure.ac
rm -f libtool
rm -f Makefile
rm -f Makefile.fragments
rm -f Makefile.objects
rm -rf build
rm -rf autom4te.cache
rm -rf modules
rm -f *.dep
rm -f *.lo
rm -f *.loT
rm -f *.la
rm -rf .libs
rm -rf cmake-build-debug